# Generated by Django 4.1.5 on 2023-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_exhibition_user_gallerypiece_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypiece',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallerypiece',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
