# Generated by Django 4.1.5 on 2023-03-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallerypiece_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypiece',
            name='image',
            field=models.ImageField(null=True, upload_to='piece-images'),
        ),
    ]
