# Generated by Django 4.1.5 on 2023-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_gallerypiece_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
