# Generated by Django 4.1.5 on 2023-04-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_exhibition_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='name',
            new_name='title',
        ),
    ]
